-- stock definition

-- Drop table

-- DROP TABLE stock;

CREATE TABLE stock (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_date timestamp(6) NULL,
	description varchar(255) NOT NULL,
	last_update timestamp(6) NULL,
	"name" varchar(255) NOT NULL,
	current_price numeric(38, 2) NOT NULL,
	CONSTRAINT stock_pkey PRIMARY KEY (id),
	CONSTRAINT uk9fjf4aj1d5f2m6wi2uqmdan0a UNIQUE (name)
);


-- stock_exchange definition

-- Drop table

-- DROP TABLE stock_exchange;

CREATE TABLE stock_exchange (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_date timestamp(6) NULL,
	description varchar(255) NOT NULL,
	last_update timestamp(6) NULL,
	"name" varchar(255) NOT NULL,
	live_in_market bool NOT NULL,
	CONSTRAINT stock_exchange_pkey PRIMARY KEY (id),
	CONSTRAINT ukcorjusnywadeyc44m8fhvg8mc UNIQUE (name)
);


-- stock_exchange_stock definition

-- Drop table

-- DROP TABLE stock_exchange_stock;

CREATE TABLE stock_exchange_stock (
	stock_exchange_id int8 NOT NULL,
	stock_id int8 NOT NULL,
	CONSTRAINT stock_exchange_stock_pkey PRIMARY KEY (stock_exchange_id, stock_id),
	CONSTRAINT fk9jxh4gfh6lfo658cwj030yat2 FOREIGN KEY (stock_exchange_id) REFERENCES stock_exchange(id),
	CONSTRAINT fkp6v3wvqmnaber2woymngrsuoe FOREIGN KEY (stock_id) REFERENCES stock(id)
);